language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
dist: trusty
install:
  - pip install .
  - pip install keyrings.alt
  - pip install coverage
  - pip install coveralls
  - pip install flake8
script:
  - flake8 --ignore E501,E722
  - coverage run --source=aws_google_auth/ --omit=aws_google_auth/tests/* setup.py test
after_script:
  - coverage report
after_success:
  - coveralls

# These are the stages. There's always a default 'Test' stage, where one of each
# is automatically run for every python version in the matrix defined above
# The 'deploy' stage is only invoked once, using python 2.7, because we do not need
# to publish multiple times.
jobs:
  include:
  - stage: Docker Build Test
    script: docker build -f Dockerfile .
    python: '3.6'
  - stage: Docker Build Test
    script: docker build -f Dockerfile.python2 .
    python: '2.7'
  - stage: deploy
    python: '2.7'
    install: skip
    script: skip
    deploy:
      provider: pypi
      username: nonspecialist
      password:
        secure: kkbjBg1MwRhyPPabNQcYreTsFexf+1/5W4soO6MWslgPQDsB3h63QfTOV5OvBFAJdBDjPFcrG8raH4JL6oebadVbl/gTYeNCpu7iSbudlSnHTgm4G84o2IOrnFDrEE7iTxkzasPAkmdhBde6ZLIbJFKJ5x5c4LQeHZZSPvYftN043Sv4yta/xeQ84iHsRGVZ/8ugXtmaiZX1rbjqpUqXe/WlR7z3O48KBFSEagZZA93fQdCQEC25SJ5J5P+WgrWyNncK8zaIl5O0k5VzfjSXrwzUl+GTA4SFkqPqj66tqJzgHIl7Ggu5D2kEY2U2+JDYaQz5bcv+WwlkE/De4DicwMoLL7Mjn2MnL2W6uSAtrkX8VoebzbSnmC4/JFC4FiPvPFiBVeO5uupsijoU7UXhYjEvLv/L0tRRo2F3PIzFTRq34KvuT60dfbnagRxp764jiXwRj9gDqbjGXqPIEf2itllOd+aur2YTjVBMQ6Nv5+C0P1wiqlHcNeeg8OY7t6e9WQHbe6iqb2ZhTQ9AgA5MEmVQRWzTD3joqY536kNcIWrbwlQ06+JhbcXlgozPwX4MiSYKtxXMXsom29wiWMzL3MJTIUOsOBe/eOWCBolYEl0Km5zr5C0gXyKZ3+4kXaG5tyGa+wjSuCXz4D01DRoK9wXDSxi+ZpHM5RYdxcAO3uY=
      on:
        tags: true

notifications:
  slack:
    secure: G5o2qR8G+i4jhIg7Hah8R+Uio2ri/3lzTeY9jBmyMPrFRnXzAlyPhHD/oyf2HCyxuc+VFi479pkTpCHXE8Jddzzrr3K3tfkyYqWC1Z/v8jNBrYqbhgBDU/geqV/w1QARAXRgViqV22kXYus0Dojk3WKBVtwoOKyRpZpDXRa9h8SYOgtd1OIR4L/uqIGSPExM0s+NoYr0eNWNP9tK2ltlKKynUF9vtxs7YAxaEd9LFPkrfGPgbsySYOKLP50B9kAP+6pVCvsWDyqQQraDUfjAIOGA8RohfehlWzVJVoKyIz/C4fQrv+zJNeOYM5eYTnRt0StXhopw6x0k8k0Hwd2KSXI1Xt/1HqmYW5eXJLf6+poYwfsv+zv+6G5an8pNVmcCBkCsvyhc56iRaDccqzvMrWoyvfMWpLstvTLRWXD5VlHEoJYYrKzh8J4ensDriv/a2jPFM8xYebzuyfqrVwwVGBO0qeqUpHNEBaD1xKQz02aRqLS7nVvYZLdgp5OEZ0fkVEbDiq5g0PWxTGsEMkk3eYjrv8QU6xNfyuufM5xV7OB+UaeIZqsf8m0tjOQ/9pXAhRaOZgnTys3x+20eMr1G6did4a0qYduDUihOL8lgFAvXqEBgxqNTRyEEIItw2tIMQbtxIILIUSxFbZ+6LIzGZF6b7Y1OAjPRh7kcHa7Aj4s=
